"use client";

export default function Terms() {
  return (
    <div style={{minHeight:"100vh",background:"#f5f3ef",color:"#0a0a0a",fontFamily:"Plus Jakarta Sans, system-ui, sans-serif",padding:"60px 20px"}}>
      <div style={{maxWidth:720,margin:"0 auto"}}>
        <div style={{marginBottom:40}}>
          <a href="https://studio.buildwithtav.co" style={{color:"#BB9900",fontWeight:700,textDecoration:"none",fontSize:14}}>← Back to Carousel Studio</a>
        </div>
        <h1 style={{fontSize:32,fontWeight:800,marginBottom:8}}>Terms of Service</h1>
        <p style={{color:"#888",fontSize:13,marginBottom:40}}>Last updated: June 2026</p>

        {[
          {
            title: "1. About Carousel Studio",
            body: "Carousel Studio is a web-based AI content generation tool operated by Build with Tav, a sole trader business based in the United Kingdom. By using Carousel Studio you agree to these terms. If you do not agree, please do not use the service.\n\nContact: tav@buildwithtav.co"
          },
          {
            title: "2. Your Account",
            body: "You must provide a valid email address to use Carousel Studio. You are responsible for maintaining the security of your account. You must not share your account with others or attempt to circumvent usage limits by creating multiple accounts. We reserve the right to suspend or terminate accounts that violate these terms."
          },
          {
            title: "3. Subscription Plans & Credits",
            body: "Carousel Studio offers a free tier and paid subscription plans (Starter and Pro). Credits are allocated monthly and do not roll over. Free tier credits are a one-time trial allocation.\n\nPayments are processed securely via Stripe. Subscriptions renew automatically each month unless cancelled. You may cancel at any time — your access continues until the end of your current billing period.\n\nRefunds are not provided for partial months except at our sole discretion."
          },
          {
            title: "4. Fair Usage Policy",
            body: "Pro plan subscribers receive unlimited credits subject to a fair usage limit of 300 credits per month. This limit exists to prevent automated abuse and ensure service quality for all users.\n\nFair usage limits are subject to change at any time with reasonable notice. We will not reduce limits without notifying active subscribers in advance.\n\nAccounts found to be using the service in an automated or abusive manner may be suspended without notice."
          },
          {
            title: "5. AI-Generated Content",
            body: "Content generated by Carousel Studio is produced by AI and may not always be accurate, appropriate, or suitable for your specific use case. You are solely responsible for reviewing, editing, and approving any content before publishing it.\n\nBuild with Tav makes no warranties regarding the quality, accuracy, or fitness for purpose of AI-generated content."
          },
          {
            title: "6. Intellectual Property",
            body: "Content you generate using Carousel Studio belongs to you. You retain full ownership of your brand settings, uploaded images, and generated outputs.\n\nThe Carousel Studio platform, its design, code, and underlying systems remain the intellectual property of Build with Tav. You may not copy, reverse engineer, or redistribute any part of the platform."
          },
          {
            title: "7. Prohibited Use",
            body: "You must not use Carousel Studio to generate content that is unlawful, harmful, defamatory, discriminatory, or in violation of any third party rights. You must not use the service to generate spam, misinformation, or content designed to deceive.\n\nWe reserve the right to remove content and suspend accounts that violate these prohibitions."
          },
          {
            title: "8. Service Availability",
            body: "We aim to keep Carousel Studio available at all times but do not guarantee uninterrupted access. The service may be temporarily unavailable due to maintenance, updates, or circumstances beyond our control.\n\nWe are not liable for any loss caused by service downtime or interruptions."
          },
          {
            title: "9. Limitation of Liability",
            body: "To the maximum extent permitted by law, Build with Tav shall not be liable for any indirect, incidental, or consequential damages arising from your use of Carousel Studio. Our total liability to you shall not exceed the amount you have paid us in the 3 months prior to any claim."
          },
          {
            title: "10. Changes to These Terms",
            body: "We may update these terms from time to time. We will notify active subscribers of significant changes by email. Continued use of the service after changes constitutes acceptance of the updated terms."
          },
          {
            title: "11. Governing Law",
            body: "These terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales."
          },
          {
            title: "12. Contact",
            body: "For any questions about these terms, contact us at tav@buildwithtav.co."
          },
        ].map(({title, body})=>(
          <div key={title} style={{marginBottom:32}}>
            <h2 style={{fontSize:16,fontWeight:800,marginBottom:10}}>{title}</h2>
            {body.split("\n\n").map((para,i)=>(
              <p key={i} style={{fontSize:14,lineHeight:1.8,color:"#333",margin:"0 0 12px"}}>{para}</p>
            ))}
          </div>
        ))}

        <div style={{borderTop:"1px solid #e0ddd8",paddingTop:24,marginTop:40,display:"flex",gap:24,flexWrap:"wrap"}}>
          <a href="/privacy" style={{color:"#BB9900",fontWeight:700,textDecoration:"none",fontSize:13}}>Privacy Policy</a>
          <a href="https://studio.buildwithtav.co" style={{color:"#BB9900",fontWeight:700,textDecoration:"none",fontSize:13}}>Back to Carousel Studio</a>
          <span style={{fontSize:13,color:"#888"}}>© 2026 Build with Tav</span>
        </div>
      </div>
    </div>
  );
}
